import '@/config/styles/index.scss';
import { ThemeProvider } from '@mui/material/styles';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Noto_Sans as notoSansFont } from 'next/font/google';

import { AuthMiddleware } from '@/config/middlewares';
import theme from '@/config/styles/theme/theme';
import { StoreProvider } from '@/providers';
import { classNames } from '@/shared/lib';
import { MainContent, Sidebar, sidebarList } from '@/widgets';

import styles from './layout.module.scss';

import type { Metadata } from 'next';

const notoSans = notoSansFont({
  variable: '--font-noto-sans',
  subsets: ['latin', 'cyrillic'],
  weight: ['200', '300', '400', '500', '600', '700'],
  style: ['normal'],
});

export const metadata: Metadata = {
  title: 'Main page',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html
      lang='en'
      className={notoSans.variable}
    >
      <body>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            <AuthMiddleware>
              <StoreProvider>
                <div className={classNames(styles.rootLayout)}>
                  <Sidebar sidebarList={sidebarList} />
                  <MainContent>{children}</MainContent>
                </div>
              </StoreProvider>
            </AuthMiddleware>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
};

export default RootLayout;
