import { type FC } from 'react';

import type { Metadata } from 'next/types';

export const metadata: Metadata = {
  title: 'About page',
  description: 'Generated by create next app',
};

const Home: FC = () => {
  return <div>page</div>;
};

export default Home;
