import { classNames } from '@/shared/lib';

import styles from './layout.module.scss';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Todo',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return <div className={classNames(styles.todoLayout)}>{children}</div>;
};

export default RootLayout;
