import { NavigationMenuHorizontal } from '@/shared';
import { classNames, ProfileLinkList } from '@/shared/lib';

import styles from './layout.module.scss';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Profile',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <div className={classNames(styles.profileLayout)}>
      <NavigationMenuHorizontal items={ProfileLinkList} />
      <div className={classNames(styles.profileLayoutContent)}>{children}</div>
    </div>
  );
};

export default RootLayout;
