name: CI pipeline
on: [push, pull_request]
jobs:
  setup-dependencies:
    name: Install dependencies
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest]
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.pnpm-cache.outputs.cache-key }}
      store-path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.11.0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: pnpm
      - name: Get pnpm store directory
        id: pnpm-store
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Cache pnpm dependencies
        id: pnpm-cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.pnpm-store.outputs.STORE_PATH }}
            node_modules
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-
      - name: Cache application build
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.next/cache
          key: nextjs-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            nextjs-${{ runner.os }}-
      - name: Print versions
        run: |
          git --version
          node --version
          pnpm --version
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright
        run: pnpm exec playwright install --with-deps

  lint:
    name: Linting typescript and scss
    runs-on: ubuntu-latest
    needs: setup-dependencies
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.11.0
      - name: Restore pnpm cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ needs.setup-dependencies.outputs.store-path }}
            node_modules
          key: ${{ needs.setup-dependencies.outputs.cache-key }}
      - name: linting typescript
        run: pnpm lint:ts
      - name: linting scss
        run: pnpm lint:scss

  build:
    name: Building artifacts
    strategy:
      matrix:
        target: [app, storybook]
    runs-on: [ubuntu-latest]
    needs: [setup-dependencies, lint]
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.11.0

      - name: Restore pnpm cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ needs.setup-dependencies.outputs.store-path }}
            node_modules
          key: ${{ needs.setup-dependencies.outputs.cache-key }}

      - name: Restore Next.js cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.next/cache
          key: nextjs-${{ runner.os }}-${{ github.sha }}

      - name: Build application
        if: matrix.target == 'app'
        run: pnpm build:app
        
      - name: Build Storybook
        if: matrix.target == 'storybook'
        run: pnpm build:sb

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-build
          path: |
            ${{ matrix.target == 'app' && 'out' || 'storybook-static' }}

  test:
    name: Run all tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.11.0

      - name: Restore pnpm cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ needs.setup-dependencies.outputs.store-path }}
            node_modules
          key: ${{ needs.setup-dependencies.outputs.cache-key }}

      # - name: Restore dependencies
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       ${{ env.STORE_PATH }}
      #       .pnpm-store
      #       node_modules
      #     key: ${{ needs.setup-dependencies.outputs.cache-key }}
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: '*-build'
          merge-multiple: true

      - name: Start application server
        run: |
          pnpm exec serve artifacts/app-build -l 3000 &
          echo "APP_SERVER_PID=$!" >> $GITHUB_ENV
          pnpm exec wait-on http://localhost:3000
          
      - name: Start Storybook server
        run: |
          pnpm exec serve artifacts/storybook-build -l 6006 &
          echo "STORYBOOK_SERVER_PID=$!" >> $GITHUB_ENV
          pnpm exec wait-on http://localhost:6006

      - name: Run Playwright tests
        run: pnpm test:endToEnd
        env:
          APP_URL: http://localhost:3000
          STORYBOOK_URL: http://localhost:6006

      - name: Stop servers
        if: always()
        run: |
          kill $APP_SERVER_PID || true
          kill $STORYBOOK_SERVER_PID || true