name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run endToEnd tests
      run: pnpm test:endToEnd
    - uses: actions/upload-artifact@v4
      env:
        CI: true
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-endToEnd
        path: playwright-report/endToEnd
        retention-days: 30
    - name: Run snapshot tests
      run: pnpm test:snapshot
    - uses: actions/upload-artifact@v4
      env:
        CI: true
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-snapshot
        path: playwright-report/snapshot
        retention-days: 30
